[general]
import = ["~/.alacritty-font-size.toml", "~/.alacritty.theme.toml"]

[env]
TERM = "xterm-256color"
SHELL = "/opt/homebrew/bin/nu"

[terminal]
shell = { program = "/opt/homebrew/bin/nu" }

[font.bold]
family = "MonaspiceNe NFM"
style = "Bold"

[font.italic]
family = "MonaspiceNe NFM"
style = "Italic"

[font.normal]
family = "MonaspiceNe NFM"
style = "Regular"

[font.offset]
y = 2

[window]
option_as_alt = "Both"
