# Based on rosebones_light
[colors.bright]
black = "#E8C48B"
blue = "#407D88"
cyan = "#407D88"
green = "#1C5970"
magenta = "#855AAC"
red = "#A54A66"
white = "#A4635F"
yellow = "#C68223"

[colors.cursor]
cursor = "#724341"
text = "#FBF6F0"

[colors.normal]
black = "#FBF6F0"
blue = "#5795A0"
cyan = "#5795A0"
green = "#286A84"
magenta = "#917BA9"
red = "#B5637A"
white = "#724341"
yellow = "#EC9D33"

[colors.primary]
background = "#FBF6F0"
foreground = "#724341"
