# This file is auto-generated by shipwright.nvim

# 👇 this controls the actual background of the status bar
set -g status-style bg=colour8

# 👇 this controls the active tab, fg=black is really white because Alacritty remaps the color
set -g window-status-current-style fg=black,bg=colour3
