prSections:
- title: My Pull Requests
  filters: is:open author:@me org:TrueLayer
- title: Needs My Review
  filters: is:open review-requested:@me org:TrueLayer
- title: Involved
  filters: is:open involves:@me -author:@me org:TrueLayer
issuesSections:
- title: My Issues
  filters: is:open author:@me org:TrueLayer
- title: Assigned
  filters: is:open assignee:@me org:TrueLayer
- title: Involved
  filters: is:open involves:@me -author:@me org:TrueLayer
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 50
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths: {}
pager:
  diff: delta
